config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "lists#index"

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to  :movie
  belongs_to  :list
  validates   :comment, presence: true, length: { minimum: 6 }
  validates   :list_id, presence: true, uniqueness: { scope: :movie_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many    :bookmarks, dependent: :destroy
  has_many    :movies, through: :bookmarks
  validates   :name, presence: true, uniqueness: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, uniqueness: true, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new', status: unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = List.find(params[:list_id])

    if @bookmark.destroy
      redirect_to list_path(@list)
    else
      render 'lists/show', status: unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render "new", status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add bookmark for <%= @list.name %> movie list</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :movie_id, collection: Movie.all %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="d-flex flex-row justify-content-between">
    <h1>Index</h1>
    <%= link_to "Create New List", new_list_path, class: "btn btn-primary my-auto" %>
  </div>
  <div class="d-flex flex-row justify-content-between row-cols-3 gap-3">
    <% @lists.each do |list| %>
      <div class="card-category " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
        <%= link_to list.name, list_path(list)%>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Create New List</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit 'Add list', class: "btn btn-primary mt-3" %>
<% end %>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>
  <%= link_to "back to lists", lists_path %>
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card-product my-2">
      <%= image_tag bookmark.movie.poster_url, alt: bookmark.movie.title %>
      <div class="card-product-infos">
        <h2><%= bookmark.movie.title %> - ⭐️ <%= bookmark.movie.rating %></h2>
        <p><%= bookmark.movie.overview %></p>
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-comment"></i><em><%= bookmark.comment %></em></p>
          <%= link_to list_bookmark_path(@list, bookmark), { data: { turbo_method: :delete, turbo_confirm: 'ok?' }} do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <p class="text-center">
    <%= link_to new_list_bookmark_path(@list) do %><i class="fa-solid fa-circle-plus"></i><% end %>
  </p>
</div>